### ISSUE TITLE
Melpa package not found.

### ISSUE THREAD

**Issue by proofit404** [polymode/poly-rst#2]

**Comment by vspinu** [comment]
It's not on melpa as yet. I had in plan to finish the poly-python and push several packages at once in order to avoid bothering MELPA folks too much. Unfortunately the past 3 months were a bit crazy and that didn't happen. I will have a look as soon as I can, but probably not before end of March because of the traveling.

**Comment by Xaldew** [comment]
I actually started preparing the repo for submission to MELPA yesterday (build fixes, checkdoc, linting, etc) and I had originally intended to submit a request pull request to MELPA sometime this week, but do you want me to wait with that until the `poly-python` package is ready @vspinu ?

**Comment by vspinu** [comment]
> but do you want me to wait with that until the `poly-python` package is ready

Not if you want to put an immediate effort into it :) 

> build fixes, checkdoc, linting, etc)

Thanks, but please keep in mind that you cannot directly modify the Makefile. Makefile is a result of a template generation/update from `polymode`'s `make template../poly-rst`. So all changes should be generic and should be done in `polymode/template/Makefile` instead.

**Comment by Xaldew** [comment]
> > but do you want me to wait with that until the poly-python package is ready

> Not if you want to put an immediate effort into it :)

It's mostly done, so I'll handle it then :)

> > build fixes, checkdoc, linting, etc)

> Thanks, but please keep in mind that you cannot directly modify the Makefile. Makefile is a result of a template generation/update from polymode's make template../poly-rst. So all changes should be generic and should be done in polymode/template/Makefile instead.

Good thing that you mentioned that! I'll submit a pull-request with the build-fixes to `poly-mode` instead of pushing them here. Just out of interest, are those kind of conventions documented somewhere? I wasn't able to find anything about that, but then again I didn't look very hard.

**Comment by Xaldew** [comment]
Pull request submitted to MELPA in melpa/melpa#6037.

**Comment by Xaldew** [comment]
`poly-rst` is now available on MELPA, so closing the issue.
